### ISSUE TITLE
有些USB接口不能用？

### ISSUE THREAD

**Issue by libern** [xinsui01/hackintosh_ASUS_ROG_Z390#1]
感谢分享

**Comment by xinsui01** [comment]
Hello @libern ，USB  需要定制，我上传了一份 UsbMap（OpenCore 引导上试了下暂时没发现问题），你可以试试。clover 引导我后面不在维护了，现在切换到了OpenCore 引导，如果有兴趣，可以切换到 OpenCore。

**Comment by xinsui01** [comment]
The usb mapping has been updated.

![USB Mapping Definition](https://github.com/xinsui01/hackintosh_ASUS_ROG_Z390/raw/master/usbMap/USB_definition.png)
