### ISSUE TITLE
OC 和 Clover不支持 UHD630核显？以及4k的核显hdmi输出？

### ISSUE THREAD

**Issue by libern** [xinsui01/hackintosh_ASUS_ROG_Z390#3]
OC 和 Clover不支持 UHD630核显？以及4k的核显hdmi输出？

进度条跑到90%直接没信号

**Comment by xinsui01** [comment]
不好意思，我使用DP输出4k, OC 和 Clover 支持 UHD630 核显的，我这里没有hdmi 线，明天我找条线看看。

**Comment by libern** [comment]
我是同款主板，我使用dp的线，开机是主板显示白色vga报错灯，是我哪里配置有问题吗？可以加个联系方式吗

**Comment by xinsui01** [comment]
可以的，我 wx： CUG_HB

**Comment by dronbana** [comment]
My USB ports won't work at all, any workaround guys?
Thanks.

**Comment by xinsui01** [comment]
已经支持HDMI了哈
