### ISSUE TITLE
No USB ports working other than USB 2.0

### ISSUE THREAD

**Issue by dronbana** [xinsui01/hackintosh_ASUS_ROG_Z390#4]
Greetings,
Thank you for the EFI, it installs perfectly and even got my bluetooth working somehow.
My only issue is that only the two USB 2.0 ports are working, none of the others are.
Is there something i'm missing on? Please help.

Warm Regards,
D

**Comment by xinsui01** [comment]
Hi，

You can follow the video and use Hackintool to customize your USB drive step by step.

Best Regards (*￣︶￣)

**Comment by xinsui01** [comment]
The usb mapping has been updated.

![USB Mapping Definition](https://github.com/xinsui01/hackintosh_ASUS_ROG_Z390/blob/master/usbMap/USB_definition.png)

**Comment by dronbana** [comment]
You're awesome, thanks a lot!
