### ISSUE TITLE
安装时，剩余大概十分钟的时候报错如下

### ISSUE THREAD

**Issue by liuxu379** [xinsui01/hackintosh_ASUS_ROG_Z390#5]
![image](https://user-images.githubusercontent.com/21291399/99413804-1ce77800-2931-11eb-88a8-f085065cb2dc.jpeg)
![image](https://user-images.githubusercontent.com/21291399/99413835-27097680-2931-11eb-99a4-ef8bdc23c24b.jpeg)

**Comment by xinsui01** [comment]
我刚开始是通过系统升级，剩余xxx分钟结束时会推出安装程序，没升级成功。❌
后来是通过制作安装U盘升级成功的。✅

我的升级步骤，希望能帮到你：
1. 制作安装U盘
    - [如何创建可引导的 macOS 安装器](https://support.apple.com/zh-cn/HT201372)
2. 重启，选择 Install macOS Big Sur

  > 安装过程中会重启多次

**Comment by liuxu379** [comment]
> 我刚开始是通过系统升级，剩余xxx分钟结束时会推出安装程序，没升级成功。❌
> 后来是通过制作安装U盘升级成功的。✅
> 
> 我的升级步骤，希望能帮到你：
> 
> 1. 制作安装U盘
>    
>    * [如何创建可引导的macOS安装器](https://support.apple.com/zh-cn/HT201372)
> 2. 重启，选择安装macOS Big Sur
> 
> > 安装过程中会重启多次

我已经搞成功了，应该BIOS里面的某些参数的设置问题。WiFi和蓝牙也可以了。

**Comment by xinsui01** [comment]
> > 我刚开始是通过系统升级，剩余xxx分钟结束时会推出安装程序，没升级成功。❌
> > 后来是通过制作安装U盘升级成功的。✅
> > 我的升级步骤，希望能帮到你：
> > 
> > 1. 制作安装U盘
> >    
> >    * [如何创建可引导的macOS安装器](https://support.apple.com/zh-cn/HT201372)
> > 2. 重启，选择安装macOS Big Sur
> > 
> > > 安装过程中会重启多次
> 
> 我已经搞成功了，应该BIOS里面的某些参数的设置问题。WiFi和蓝牙也可以了。

自己动手丰衣足食👍

可以贴下你改了BIOS设置哪几项不，留给遇到相同问题小伙伴，O(∩_∩)O哈哈~
