### ISSUE TITLE
config.plist

### ISSUE THREAD

**Issue by ericvipo** [xinsui01/hackintosh_ASUS_ROG_Z390#7]
**Can you share your config file config.plist?**
is that I have my computer very similar to yours, my hardware is:

  - CPU: Intel Core i9-9900K
  - GPU: VGA GIGABYTE RADEON RX VEGA 56 GAMING OC 8GB HBM2
  - MB: ASUS ROG STRIX Z390-E GAMING WI-FI LGA 1151
  - RAM: 2 x CORSAIR VENGEANCE LPX, 16GB DDR4 3200 MHZ
  - SSD: 2 x M.2 PCIe 250GB Kingston KC2500
  - HDD: SEAGATE BARRACUDA 2TB 7200 RPM

**Did you install a new wifi adapter or is it the same one that the motherboard comes with?**
works wifi?

Could you please share your config.plist file so i can guide me?

**Comment by ericvipo** [comment]
> 
> 
> _No description provided._

**Comment by xinsui01** [comment]
@ericvipo The early drivers were not perfect, and a software was required to be installed. At the same time, wifi is not necessary for desktop computers. Therefore, I did not add the Airportltlwm driver.

Now, I added the driver to config.
